defaults:
  - logger

template: "inference/zero_shot_template_v3.j2"

logger:
  record: True
  group: "fineTune"
  save_model: False

train:
  train_batch_size: 4 # this might need to go down for larger models
  val_batch_size: 8
  model_name: "mistralai/Mistral-7B-v0.1" #"mistralai/Mistral-7B-v0.1" # "mistralai/Mistral-7B-Instruct-v0.1"
  max_length: 275
  save_override: null
  lora_r: 16 # experiment with 32
  lora_alpha: 16 # experiment with 32
  lora_dropout: 0.05
  gpu_num: 0
  num_epochs: 5
  eval_frac: null
  lr: 1e-5
  init_eval: True
  questions_path: 'cleaned/questions_cleaned_v1.csv'
  train_responses_path: 'splits/folds/response/sample_small_train_8.csv'
  val_responses_path: 'splits/folds/response/sample_small_val_8.csv'
